import {
  Box,
  Divider,
  Stack,
  StackDivider,
  Text,
  useColorModeValue as mode,
} from '@chakra-ui/react'
import * as React from 'react'
import { FaMobileAlt, FaShieldAlt } from 'react-icons/fa'
import { Description } from './Description'

export const App = () => {
  return (
    <Box as="section" bg={mode('gray.100', 'inherit')} py="12">
      <Box maxW={{ base: 'xl', md: '7xl' }} mx="auto" px={{ md: '8' }}>
        <Box
          rounded={{ lg: 'lg' }}
          bg={mode('white', 'gray.700')}
          maxW="3xl"
          mx="auto"
          shadow="base"
          overflow="hidden"
        >
          <Box px="6" py="4">
            <Text as="h3" fontWeight="bold" fontSize="lg">
              Verification options
            </Text>
            <Text color={mode('gray.600', 'gray.300')} fontSize="sm">
              Add an extra layer of security to block unauthorized access and protect your account.
            </Text>
          </Box>
          <Divider />
          <Stack spacing="6" divider={<StackDivider />} py="5" px="8">
            <Description isRecommended title="Authenticator" icon={<FaShieldAlt />}>
              Enter a code generated by your authenticator app to confirm it’s you.
            </Description>
            <Description title="Mobile app prompt" icon={<FaMobileAlt />}>
              Receive a prompt from your mobile app to confirm it’s you.
            </Description>
          </Stack>
        </Box>
      </Box>
    </Box>
  )
}
